services:
  smart-campus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-campus
    restart: unless-stopped
    working_dir: /app
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      PORT: "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - smartcampus_node_modules:/app/node_modules

volumes:
  smartcampus_node_modules:
